### ISSUE TITLE
Add custom jar for running db migrations for new deployments

### ISSUE THREAD

**Issue by abarciauskas-bgse** [nasa/Common-Metadata-Repository#1235]
Following discussions with the NOAA team who have been deploying new instances of CMR, it sounds like @chris-durbin and @littleidiot40 created a custom jar to fix some runtime / chicken and egg issue with a new CMR deployment. From what I understood, certain services - legacy services, metadata-db and ingest - may fail to come up when trying to come up as healthy before the database migrations are run.

It would be great if that updated database migration code could be contributed back here or to the cmr-cloud-deployments repository so that new deployments could run successfully.

From what I understand the jar "created the minimum sql migration for the service to come up. The jar extracted the sql to create the tables so that the service comes up. Then we can curl and post on the service to finish the migrations."

**Comment by tbs1979** [comment]
I don't think this is something for CMR to do since we don't do deployments for other groups.
