### ISSUE TITLE
Feature Request: add (multi)hash to granule metadata

### ISSUE THREAD

**Issue by 7yl4r** [nasa/Common-Metadata-Repository#417]
The addition of a hash value for granules would prove useful in the following ways:

* verifying the integrity of downloads
* identifying out-of-date file versions
* allowing hash-based de-duplication to eliminate repeated downloads
* support downloads over hash-indexed distributed networks like IPFS

**Comment by oubiwann** [comment]
Pinging @chris-durbin on this ... he knows about the granule features.

**Comment by chris-durbin** [comment]
We do have a larger feature request out there to support checksums in granule metadata. The scope is broader than the CMR though. The metadata model and formats will need updated to support the new fields, and the data providers will need to begin populating those fields (checksum type and checksum value).

**Comment by 7yl4r** [comment]
Thanks @chris-durbin . I know there are a lot of moving parts involved in such an addition, and I am glad to hear checksums are in the roadmap. A sha256 hash would be needed for my IPFS experiments, but I know it would be far off and that there are bigger factors to consider in choosing a checksum.

**Comment by mschmele** [comment]
@7yl4r the UMM-G schema has been updated to include Checksums. I'm not sure what the schedule is to provide that information is on other metadata formats.

The object can be found in the schema here: https://git.earthdata.nasa.gov/projects/EMFD/repos/unified-metadata-model/browse/granule/v1.4/umm-g-json-schema.json#258
