### ISSUE TITLE
where to report / discuss missing metadata?

### ISSUE THREAD

**Issue by 7yl4r** [nasa/Common-Metadata-Repository#420]
I have identified a gap in modis aqua l1a CMR  records as shown by the following query:

https://cmr.earthdata.nasa.gov/search/granules.json?short_name=MYD01&page_num=1&sort_key=-revision_date&temporal=2002-07-29T20:15:01Z,2002-08-08T00:25:01Z&page_size=50

Presently the above query only returns two granules with `time_start`s

*    2002-07-29T20:15:00.000Z
*    2002-08-08T00:25:00.000Z

everything in between is missing. We expect to see one granule every 5 minutes.

Are these granules missing, intentionally left out, or simply not currently hosted by a DAAC?

Please direct me if there is a better place for this discussion.

**Comment by oubiwann** [comment]
This is definitely a good place to make an initial report ... let's see what the rest of the team has to say about this (they might have a good suggestion on the next steps).

**Comment by 7yl4r** [comment]
thanks for triaging these @oubiwann . I'm currently running through all modis aqua l1 granules and will add to this issue if I come across any other gaps for that collection.

**Comment by mschmele** [comment]
@7yl4r these collections look to be owned by LAADS, who would be the best people to get in touch with, as the CMR does not modify metadata. Your best bet is to bring this to the DAAC's attention.

Hope some of this information is helpful!

https://ladsweb.modaps.eosdis.nasa.gov/

**Comment by 7yl4r** [comment]
thanks Mark. I will contact the metadata provider next time I come across
broken links.
