### ISSUE TITLE
Project version

### ISSUE THREAD

**Issue by dijonkitchen** [nasa/Common-Metadata-Repository#777]
Guessing [this](https://github.com/nasa/Common-Metadata-Repository/blob/master/project.clj#L15) should match with the [releases](https://github.com/nasa/Common-Metadata-Repository/releases).

**Comment by mschmele** [comment]
Hey sorry, we managed to miss this one! We haven't been incrementing the snapshot versions in the `project.clj` files. It's on the list of eventual things to do, but it hasn't ever been prioritized
